import {
  BookOpen,
  Bookmark,
  Briefcase,
  Camera,
  Code,
  Coffee,
  Compass,
  Feather,
  Flame,
  Folder,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  Lightbulb,
  MapPin,
  Music,
  Palette,
  Plane,
  Shield,
  Sparkles,
  Star,
  Sun,
  Target,
  Trophy,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const COLLECTION_ICONS: Record<string, LucideIcon> = {
  "book-open": BookOpen,
  lightbulb: Lightbulb,
  sparkles: Sparkles,
  folder: Folder,
  plane: Plane,
  heart: Heart,
  briefcase: Briefcase,
  "graduation-cap": GraduationCap,
  bookmark: Bookmark,
  camera: Camera,
  code: Code,
  coffee: Coffee,
  compass: Compass,
  feather: Feather,
  flame: Flame,
  globe: Globe,
  headphones: Headphones,
  "map-pin": MapPin,
  music: Music,
  palette: Palette,
  shield: Shield,
  star: Star,
  sun: Sun,
  target: Target,
  trophy: Trophy,
  zap: Zap,
};

/** Soft tints, readable in light and dark mode. */
export const COLLECTION_COLORS: Record<string, string> = {
  saffron: "bg-[#f3e6d3] text-[#7a4e1a] dark:bg-[#2e2a22] dark:text-[#e4b777]",
  sage: "bg-[#e3ebdf] text-[#3f5a37] dark:bg-[#232b22] dark:text-[#a9c39e]",
  dusk: "bg-[#e6e3f0] text-[#4a4470] dark:bg-[#26243a] dark:text-[#b7b0e0]",
  rose: "bg-[#f3e1df] text-[#7d3b33] dark:bg-[#2f2221] dark:text-[#e0a79f]",
  sky: "bg-[#dfe9f0] text-[#2f5670] dark:bg-[#1f2a33] dark:text-[#9dc2dc]",
  emerald: "bg-[#dcfce7] text-[#15803d] dark:bg-[#143823] dark:text-[#86efac]",
  violet: "bg-[#f3e8ff] text-[#6b21a8] dark:bg-[#311b47] dark:text-[#d8b4fe]",
  amber: "bg-[#fef3c7] text-[#b45309] dark:bg-[#36270d] dark:text-[#fcd34d]",
  crimson: "bg-[#ffe4e6] text-[#be123c] dark:bg-[#3f121d] dark:text-[#fda4af]",
  coral: "bg-[#ffedd5] text-[#c2410c] dark:bg-[#3c1b0d] dark:text-[#fdba74]",
  indigo: "bg-[#e0e7ff] text-[#3730a3] dark:bg-[#1e2348] dark:text-[#a5b4fc]",
  teal: "bg-[#ccfbf1] text-[#0f766e] dark:bg-[#113532] dark:text-[#5eead4]",
};
